__author__ = 'Keith Hannon'
__datecreated__ = '8/07/2015'
SYSTEM_LEVEL_FIELD_NAMES =  ['altitude'
                            ,'assigned_to'
                            ,'assigned_to_id'
                            ,'client_created_at'
                            ,'client_updated_at'
                            ,'course'
                            ,'created_at'
                            ,'created_by'
                            ,'created_by_id'
                            ,'form_id'
                            ,'id'
                            ,'latitude'
                            ,'longitude'
                            ,'horizontal_accuracy'
                            ,'project_id'
                            ,'status'
                            ,'version'
                            ,'speed'
                            ,'updated_at'
                            ,'updated_by_id'
                            ,'vertical_accuracy'
                            ]


